Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 30
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 8
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
Layout/LineLength:
  Enabled: true
  Max: 200
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  CountComments: false
  Max: 150
