default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'shopify_app_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'shopify_app_test' %>

production:
  <<: *default
#  database: shopify_app_production
#  username: shopify_app
#  password: <%#= ENV['SHOPIFY_APP_DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_NAME'] || 'shopify_app_production' %>
