default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'narwhal_orders_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'narwhal_orders_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || ENV['DATABASE_NAME'] || 'narwhal_orders_production' %>
