default: &default
  adapter: postgresql
  encoding: utf8
  sslmode: prefer
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: 10
  timeout: 5000
  variables:
    statement_timeout: 60000

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'narwhal_orders_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'narwhal_orders_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || ENV['DATABASE_NAME'] || 'narwhal_orders_production' %>
