<% DISABLED_DEV = !['development', nil].include?(ENV.fetch('RAILS_ENV', nil)) %>
---
:timeout: 8

development:
  :concurrency: 5
staging:
  :concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
production:
  :concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

:queues:
  - ["mailers", 3]
  - ["events", 3]
  - ["default", 2]

:enabled: true

:scheduler:
  :listened_queues_only: true

:schedule:
  # --- SAMPLE WORKER JOB ---
  job_name:
    description: "Job Description"
    cron: "0 * * * *" # Runs every hour starting at *:00
    class: "Tasks::SampleWorkerJob"
    queue: "default"
